# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: | # sh fava/update.sh, curl beancount files
      touch ledger.beancount 
      chmod 664 ledger.beancount
    init: |
      make
      pre-commit install
      pip install --editable .
      gp sync-done bundle
    command: fava --debug ledger.beancount # -p 443 
    # env:
    #   BEANCOUNT_FILE:
    #   FAVA_HOST: $(gp url 5000)
  - name: UI
    # before: cd frontend
    # init: npm install
    init: gp sync-await bundle
    command: |
      cd frontend 
      npm run dev
    openMode: split-right
  - name: Open
    command: |
      gp await-port 5000
      gp preview $(gp url 5000)/beancount/income_statement/

ports:
  - port: 5000
    onOpen: ignore # open-preview # /beancount/income_statement
    visibility: public

gitConfig:
  alias.st: status