name = "fava-container-app"
main = "worker.js"
compatibility_date = "2025-09-27"

[[containers]]
name = "fava_container"
# image = "ghcr.io/alycda/fava:latest"
image = "./Dockerfile"
class_name = "FavaContainer"

[[durable_objects.bindings]]
name = "FAVA_CONTAINER"
class_name = "FavaContainer"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["FavaContainer"]